module.exports = {
  roots: ['<rootDir>/src'],
  moduleNameMapper: {
    '^@database(.*)$': '<rootDir>/src/infrastructure/database/$1',
    '^@infrastructure(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@logger(.*)$': '<rootDir>/src/infrastructure/logger/$1',
    '^@shared(.*)$': '<rootDir>/src/shared/$1',
  },
  collectCoverageFrom: [
    '<rootDir>/src/modules/**/*.ts',
    '!<rootDir>/src/main/**',
    '!**/node_modules/**',
  ],
  coverageDirectory: './coverage',
  setupFilesAfterEnv: ['./jest.setup.js'],
  testEnvironment: 'node',
  transform: {
    '.+\\.ts$$': ['ts-jest', { isolatedModules: true }],
  },
  coverageReporters: [
    'html',
    'text-summary',
    'json-summary',
    'text',
    'lcov',
    'clover',
    'cobertura',
  ],
  coveragePathIgnorePatterns: [
    '.module.ts',
    '.dto.ts',
    '.interface.ts',
    '.mock.ts',
    'main.ts',
    'cli.ts',
    'schema.ts',
    'entity.ts',
    '.model.ts',
    'index.ts',
    '.enum',
  ],
};
